fix(bug #112): `tokens.get()` memorization
oddbird/accoutrement pull request #113
Opened 2022-05-28 10:47 UTC by enten

Bug https://github.com/oddbird/accoutrement/issues/112 describes what is fixed.

2022-06-07 17:26 UTC, mirisuzanne requested changes
Nice catch, this fix looks great! Thank you for the contribution. Can you update the changelog as well, to document this fix?

2022-07-18 12:27 UTC, enten commented
> Can you update the changelog as well, to document this fix?
Okay, but do we need to bump to version 4.0.2 in package.json too?

2022-07-18 12:27 UTC, enten commented on test/tokens/_api.scss
> +    @include it('Memorize resolved value') {
Done

2022-07-18 18:07 UTC, mirisuzanne approved these changes
Looks good! We can update the version when we release it. Thanks!

2022-07-18 18:10 UTC, merged